baseURL = "https://7ka.org/"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
title = "としつーる改"
theme = "hugo-coder"
disqusShortname = "nakkaa"
rssLimit = "5"
uglyurls = false

hasCJKLanguage = true
summaryLength = 70

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "monokai"

googleAnalytics = "UA-47272480-1"

# 関連記事を出す
[related]
  includeNewer = true
  threshold = 80
  toLower = true

[[related.indices]]
  name = "tags"
  weight = 80

[[related.indices]]
  name = "categories"
  weight = 60

[[related.indices]]
  name = "date"
  weight = 10

[params]
    author = "なっかあ"
    info = "思いつきをコードに落とせるプログラマになりたい"
    description = "なっかあの個人サイトです。コンピュータ関係のメモ書きや、自作ソフトウェアの配布を行っています。"
    keywords = "blog,developer,personal,としつーる"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "コンピュータ関係のメモ書きや、自作ソフトウェアの配布をしているサイト"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

    dateFormat = "2006/01/02"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/nakkaa/"

[[params.social]]
    name = "Unsplash"
    icon = "fas fa-camera fa-2x"
    weight = 2
    url = "https://unsplash.com/@nakkaa"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/_nakkaa/"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss fa-2x"
    weight = 4
    url = "./index.xml"

# Menu links
[[menu.main]]
    name = "自作ソフト"
    weight = 3
    url  = "/software/"
[[menu.main]]
    name = "ブログ"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "自己紹介"
    weight = 1
    url = "/about/"
