baseURL = "https://blog.7ka.org/"
languageCode = "ja"
title = "脱ムチィ育成日誌"
theme = "hugo-primer"
copyright = "&copy; 2020 ムチィ"
disqusShortname = "nakkaa"
rssLimit = "5"
uglyurls = false

hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
shareTo = ["Twitter", "Hatena", "Pocket"]
showFooterCredits = true
description = "Describe what your web page is about"
twitter = "_nakkaa"
#useIcon = true
useTwitterCard = true
math = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[menu]

  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "About"
    #pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
