baseURL = "https://blog.7ka.org/"
languageCode = "ja"
title = "としつーる改"
theme = "hugo-coder"
copyright = "&copy; 2020 nakkaa"
disqusShortname = "nakkaa"
rssLimit = "5"
uglyurls = false

hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    author = "なっかあ"
    info = "プログラマのような何か"
    description = "なっかあの個人サイトです。"
    keywords = "blog,developer,personal,としつーる"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "なっかあの個人サイト"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/nakkaa/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-mastodon fa-2x"
    weight = 3
    url = "https://ma.fono.jp/@nakkaa/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/_nakkaa/"

# Menu links
[[menu.main]]
    name = "Software"
    weight = 3
    url  = "/software/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
